# Generated by Django 5.1.3 on 2024-11-12 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_characters_product_characteristics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default="29b5de09-979a-47d5-a988-a4678cd8bdde",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
    ]
